// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	GetTransaction(ctx context.Context, id uuid.UUID) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
