// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  id,
  description,
  date,
  amount
) VALUES (
  $1, $2, $3, $4
) 
RETURNING id, description, date, amount
`

type CreateTransactionParams struct {
	ID          uuid.UUID `json:"id"`
	Description string    `json:"description"`
	Date        time.Time `json:"date"`
	Amount      float64   `json:"amount"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.Description,
		arg.Date,
		arg.Amount,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Date,
		&i.Amount,
	)
	return i, err
}

const getLatestTransactions = `-- name: GetLatestTransactions :many
SELECT
    id,
    description,
    date,
    amount
FROM 
    transactions
ORDER BY 
    ctid DESC
LIMIT $1
`

func (q *Queries) GetLatestTransactions(ctx context.Context, limit int32) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getLatestTransactions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Date,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransaction = `-- name: GetTransaction :one
SELECT
  id,
  description,
  date,
  amount
FROM 
    transactions
WHERE 
    id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Date,
		&i.Amount,
	)
	return i, err
}
